Bank backend v2
clouway-incubator/bankapp pull request #10
Opened 2017-05-04 08:27 UTC by iliyanmotovski

Contains login with authentication, logout, cookies and
session renew every time user sends new request, exept for logout

2017-05-09 06:55 UTC, iliyanmotovski commented
I will push an updated version today.

2017-05-09 08:58 UTC, iliyanmotovski commented
Current version is ready for code review.

2017-05-09 10:21 UTC, mgenov requested changes

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +func hashGenerator(u *domain.User) error {
hashGenerator is common name which indicates generator which is a noun, not a verb:

Better would be: 
```golang
hash, err := bcrypt(request.Password)
...
u.Password = hash; 
```

It's not a good idea domain user to contain password in it's original form.

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +			case "E11000 duplicate key error collection: bank.users index: username_1 dup key: { : \"" + u.Username + "\" }":
HTTP Handler knows for the persistence as it verifies "bank.users" which is the persistence logic. 


It would be better a domain error to be defined which to indicate the type of error that was encountered:
```golang
// in domain as it should act as a contract to all implementations 
var ErrUserAlreadyExists = errors.New("domain: user already exists")
```

Where in handler you will have: 
```golang
err = userStore.InsertUser(u)
if err != nil {
  if err == domain.ErrUserAlreadyExists {
       http.Error(w, "user already exists", http.StatusBadRequest) // it's better json response to be returned
       return 
  }
  http.Error(w, "a generic error", http.StatusBadRequest) // it's better json response to be returned with proper response code
  return
}

```
It's better JSON to be returned from handlers which are called from the frontend app. 

https://github.com/clouway/teamspace/wiki/REST-API-Design
Status: 422 - Unprocessable Entity response;
```javascript
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "user",
      "field": "username",
      "code": "already_exists"
    }
  ]
```

So the UI will be able to display proper error in the form.

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +func authenticate(u domain.User, usrStore domain.UserStore) (*domain.User, error) {
Move it after the user handler as it's not exported. When someone looks up the sources will search for exported types not for not exported and is more reasonable they to go first.

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +		session, err := sessStore.StartSession(time.Now().Local().Add(time.Second*300), *userFromDb)
As I can see you are passing directly the expiration time.  It will be better to be said explicitly as it will make code more readable.

```golang
expirationTime := time.Now().Local().Add(SessionDuration));  // session duration is a constant in this case
```

It would be better duration to be passed to the creation of store, as it will be in main and will be easier for users to set it up. Also it may be added as command argument option. 

```golang
store := NewSessionStore(db, sessionDuration)
```

Usage:
```golang
session, err := sessionStore.StartSession(time.Now(), *userFromDb)
```

So the logic for calculation of the duration of the session will be in sessionStore which is more reasonable to me.

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +		go renew.VoidSessionAfter(sessStore, *session)
You will not be able to test this code easily. Also it's not a good approach. If you want to update session you can to do it in the middleware as with every request comes.

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +		renew.RenewSessionCounter <- false
The number of sessions could be read from the datastore directly and you don't need this object. 

query: expiration >= currentTime

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +func DeleteUserAccount(accStore domain.AccountStore) http.Handler {
accountStore

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +		err = accStore.DeleteAccount(account.UserID, account.Currency)
accountStore.DeleteAccount should insert history on it's own, cause this design enforces the callers to call InsertHistory every time when account operation is performed.

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +		err = accStore.InsertHistory(accountID, "new account", account.Currency, account.Amount)
accountStore.InsertAccount should insert history on it's own, cause this design enforces the callers to call InsertHistory every time when account operation is performed.

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +		for _, current := range *result {
This logic should be in the persistence, as mongo already has atomic operations like: findAndUpdate. 

The following snipped
```golang
err := accountStore.Widthdraw(account,  amount)
if err != nil {
}
```
looks more reasonable to me.

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +		result, err := accStore.GetAccounts(account.UserID)
Same as withdraw.

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +		h := context.Get(r, "history")
I suppose it's a request for history not just history. 

You can shorten it on a single line: 

```golang
request := context.Get(r, "history").(domain.HistoryRequest)
```

2017-05-09 10:21 UTC, mgenov commented on bank/api/api.go
> +		result, err := accStore.GetHistory(history.AccountID)
Please be sure that accountHistory could be retrieved only for the accounts that are own by user.

2017-05-09 10:21 UTC, mgenov commented on bank/api/middleware.go
> +func CheckValidSessionOnLoginAndLogoutMiddleware(sessStore domain.SessionStore) func(http.Handler) http.Handler {
Name should be more common as it may be used not just by login and logout: 

CookieBasedSecurity sounds better.

2017-05-09 10:21 UTC, mgenov commented on bank/api/middleware.go
> +				case loginUrl:
I'm not sure that you need these url checks.

```golang
CookieBasedSecurity(sessionStore domain.SessionStore) 
```

Keep in mind that you can attach middleware to specific endpoint, so you just don't have to attach this middleware for login and logout handlers.

2017-05-09 10:21 UTC, mgenov commented on bank/api/middleware.go
> +func CheckValidSessionOnTransactionMiddleware(sessStore domain.SessionStore, accStore domain.AccountStore, renew domain.Renew) func(http.Handler) http.Handler {
I'm not sure that you need this middleware at all. Single middleware need to be used for security.

2017-05-09 10:21 UTC, mgenov commented on bank/api/middleware.go
> +func CheckValidSessionOnHistoryRequestMiddleware(sessStore domain.SessionStore, renew domain.Renew) func(http.Handler) http.Handler {
This middleware is also not required.

2017-05-09 10:21 UTC, mgenov commented on bank/domain/types.go
> +type SessionStore interface {
godoc is missing

2017-05-09 10:21 UTC, mgenov commented on bank/domain/types.go
> +type UserStore interface {
godoc is missing

2017-05-09 10:21 UTC, mgenov commented on bank/domain/types.go
> +type AccountStore interface {
godoc is missing

2017-05-09 10:21 UTC, mgenov commented on bank/domain/types.go
> +type Renew struct {
I'm not sure that you need such thing, as logout could terminate session at any time. If you don't want to add logout in this PR, then you can perform manually logout by removing cookie from the browser.

2017-05-09 10:21 UTC, mgenov commented on cmd/bankapp/main.go
> +	mongoSessionRepo := persistence.NewSessionRepository(*session, "bank")
Code uses sessionStore but here it's called: sessionsRepository

I don't mind which one to be, but only one naming convention need to be used. 

Name of variable should be just: sessionStore or sessionRepository as If I change the implementation of the store to: memory.NewInMemorySessionStore() I don't have to change on many places in my code.

2017-05-09 10:21 UTC, mgenov commented on cmd/bankapp/main.go
> +	mongoImplementedUserStore := domain.UserStore(mongoSessionRepo)
userRepository

2017-05-09 10:21 UTC, mgenov commented on cmd/bankapp/main.go
> +	mongoImplementedUserAccountStore := domain.AccountStore(mongoSessionRepo)
accountStore and sessionStore

2017-05-09 10:21 UTC, mgenov commented on cmd/bankapp/main.go
> +	mongoImplementedUserSessionStore := domain.SessionStore(mongoSessionRepo)
Looks duplicated with the sessionRepository. I think that you have separated the same thing.

2017-05-09 10:21 UTC, mgenov commented on cmd/bankapp/main.go
> +	r.Handle("/", http.FileServer(http.Dir("./bank/static")))
static should be in the current direcory. You may create a shell script which runs: npm run build 
and copies output of the build folder into static folder in the current directory. 


This is an example how we are doing it internally: 
```bash
#!/bin/bash

rm -rf static
export NODE_ENV=production

cd ../../fleerp/frontend
npm run compile

mv dist ../../cmd/app/static
cd ../../cmd/app

go run main.go "$@"

```

2017-05-09 10:21 UTC, mgenov commented on cmd/bankapp/main.go
> +	r.Handle("/users/account/manage", TransactionHandlers.Then(api.GetUserAccounts(mongoImplementedUserAccountStore))).Methods("GET")
```
GET /users/56/accounts -> GET user accounts, but you have to ensure that current user is 56
POST /users/56/accounts -> CREATE a new user account for user 56, but you have to validate that me is user 56 

or 

GET /users/me/accounts -> GET my accounts 
POST /users/me/accounts -> CREATE my own account and user id should be taken from the session 
```

cc @IvelinYR

2017-05-09 10:21 UTC, mgenov commented on cmd/bankapp/main.go
> +	r.Handle("/users/login", LoginLogoutHandlers.Then(api.LoginHandler(mongoImplementedUserSessionStore, mongoImplementedUserStore, mongoImplementedUserAccountStore, renew)))
You can use subrouter to eliminate the duplication of users and attaching of the same security middleware:

```golang
	usersRouter := router.NewRoute().Subrouter()

```

2017-05-11 06:40 UTC, iliyanmotovski commented
Since I have no questions concerning your comments, I found it not productive to answer to every single one with OK or something of that sort, but FYI I'm working on it.

2017-05-12 07:27 UTC, iliyanmotovski commented
Current version is ready for code review.

2017-05-12 07:31 UTC, iliyanmotovski commented
I unstaged the tests and didn't commit them. It is strange that they still appear in this pull request.

2017-05-12 07:52 UTC, iliyanmotovski commented
Pull request no longer contains tests.

2017-05-12 09:10 UTC, iliyanmotovski commented
Current version is ready for code review.

2017-05-15 08:46 UTC, mgenov requested changes

2017-05-15 08:46 UTC, mgenov commented on bank/api/api.go
> +		u, err := userStore.GenerateUser(request)
You can simplify api usage of the store with:

```golang
u := userStore.RegisterUser(request); 
```

t.e GenerateUser to be removed.

2017-05-15 08:46 UTC, mgenov commented on bank/api/api.go
> +			w.WriteHeader(http.StatusCreated)
You can remove the else statement by inverting the condition

```go
if err == nil {
  w.WriteHeader(http.StatusCreated)
  // TODO: write json as response

  return
} 

switch err {
   ...
}
```

2017-05-15 08:46 UTC, mgenov commented on bank/api/api.go
> +		result, err := accountStore.GetAccounts(account.UserID)
You don't need instantiation of the account.
```golang
accountStore.GetAccounts(session.UserID)
```

2017-05-15 08:46 UTC, mgenov commented on bank/api/api.go
> +		_, err := accountStore.InsertAccount(account)
InsertAccount(userID, account) will make it more explicit. This will remove and setting of the UserId in the account.

2017-05-15 08:46 UTC, mgenov commented on bank/api/api.go
> +		currency := value["currency"]
I suppose account should be deleted by it's id, not by currency.

2017-05-15 08:46 UTC, mgenov commented on bank/api/api.go
> +		historyRequest.UserID = session.UserID
GetHistory(historyRequest) 
or
GetHistory(session.UserID, accountID) // accountID could be passed as ?accountID=1234

2017-05-15 08:46 UTC, mgenov commented on bank/api/middleware.go
> +				result, err := accountStore.GetAccounts(session.UserID)
Doesn't look like it should belong here.

2017-05-15 08:46 UTC, mgenov commented on cmd/bankapp/main.go
> +	s := r.PathPrefix("/users").Subrouter()
add versioning /v1/users to the endpoint

2017-05-15 12:08 UTC, iliyanmotovski commented
Ready for review.

2017-05-15 13:33 UTC, closed without merging