Server response changes
clouway-incubator/bankapp pull request #24
Opened 2017-05-22 08:23 UTC by iliyanmotovski

Tested the app with the real frontend and the Session response needed
to be changed. Now the server sends Session only on the first User request,
when the User logged in successfully.

Fixed a bug that occurred with the real frontend, due to multiple
WriteHeader response calls.

2017-05-22 10:22 UTC, iliyanmotovski commented
Ready for review.

2017-05-22 18:52 UTC, mgenov requested changes

2017-05-22 18:52 UTC, mgenov commented on frontend/package.json
> -{
Doesn't look reasonable frontend to be deleted.

2017-05-23 06:10 UTC, iliyanmotovski commented on frontend/package.json
> -{
My bad... I'll add it.

2017-05-23 06:15 UTC, iliyanmotovski commented
Ready for review.

2017-05-23 07:04 UTC, mgenov approved these changes
LGTM !

2017-05-23 07:05 UTC, mgenov commented
You can take a look how PR title was changed.

2017-05-23 07:05 UTC, merged