Add frontend folder
clouway-incubator/bankapp pull request #8
Opened 2017-05-02 11:00 UTC by IvelinYR

The app contains, adding new accounts and making  transactions

2017-05-02 11:09 UTC, mgenov commented
Please squash your commits.

2017-05-02 22:33 UTC, mgenov requested changes

2017-05-02 22:33 UTC, mgenov commented on frontend/src/components/AccountList/MainSectionAccountList.js
> +    // constructor() {
Commented code need to be removed.

2017-05-02 22:33 UTC, mgenov commented on frontend/src/components/AccountList/MainSectionAccountList.js
> +            <AccountListContainer/>
Presentational components cannot wrap Container components. The container components should be root ones.

2017-05-02 22:33 UTC, mgenov commented on frontend/src/components/History/History.js
> +export default class History extends Component {
History is too common and may be mislead with browser history. TransactionHistory or TransactionsList or TransactionsTable are more concrete and better describe the role of the component.

2017-05-02 22:33 UTC, mgenov commented on frontend/src/container/Transaction.js
> +export default class Transaction extends Component {
This class looks really strange as it uses axios directly.

2017-05-03 08:59 UTC, IvelinYR commented
All changes are made.
Also, here I have added a login form.

2017-05-03 13:27 UTC, mgenov requested changes
Please don't add new functionalities till the existing ones are not merged.

2017-05-03 13:27 UTC, mgenov commented on frontend/src/container/Transaction.js
> +export default class Transaction extends Component {
This class is not using redux and name of it doesn't show the intention.

2017-05-03 13:27 UTC, mgenov commented on frontend/src/App.test.js
> +
these empty lines could be cleaned up.

2017-05-03 13:27 UTC, mgenov commented on frontend/src/App.test.js
> +// import {shallow} from 'enzyme';
commented lines could be removed

2017-05-09 10:38 UTC, mgenov commented on frontend/src/App.test.js
> +
.

2017-05-09 10:38 UTC, mgenov commented on frontend/src/container/Transaction.js
> +export default class Transaction extends Component {
.

2017-05-09 11:15 UTC, mgenov requested changes

2017-05-09 11:15 UTC, mgenov commented on frontend/src/App.test.js
> +    it('works', () => {
This test could be removed as it was used just for proving that tests are working.

2017-05-09 11:15 UTC, mgenov commented on frontend/src/components/AccountList/AccountList.js
> +                            account = {...account};
You don't have to copy it as it's in props.

2017-05-09 11:15 UTC, mgenov commented on frontend/src/components/AccountList/AccountListItem.js
> +export default (props) => {
You can perform type checking with prop types: 

https://facebook.github.io/react/docs/typechecking-with-proptypes.html

```javascript
AccountListItem.propTypes = {
  id: PropTypes.number.isRequired
   ...
}

```

This will let the callers know that they have to provide this prop types.

2017-05-09 11:15 UTC, mgenov commented on frontend/src/components/Header.css
> +.title {
Just for info: http://getbem.com/introduction/

2017-05-09 11:15 UTC, mgenov commented on frontend/src/components/Header.js
> +                <Link to="/home" className="back">back</Link>
https://en.bem.info/methodology/quick-start/ 

will give you some guidelines about styling.

2017-05-09 11:15 UTC, mgenov commented on frontend/src/components/Transaction/TransactionForm.js
> +        let today = new Date();
Looks duplicated in both functions deposit and withdraw. Keep in mind that it's not a good idea client to provide time as it's easy to be manipulated. The server is the one (stub in your case) which should mark the time that operation was performed. The client may pass and time just for verifications, but it shouldn't be meaningful for the server. 

You have several options about this:
1. Extract it into separate function in the component to remove duplication
2. Extract it as separate component 
3. Use timestamp and format date with components if it need to be . 

Keep in mind that it's better server to receive timestamp directly or standard date time format: https://en.wikipedia.org/wiki/ISO_8601

2017-05-09 11:15 UTC, mgenov commented on frontend/src/reducers/account.js
> +
empty lines could be removed.

2017-05-09 11:15 UTC, mgenov commented on frontend/src/reducers/login.js
> +            browserHistory.push('/login');
Looks strange browserHistory to be used that way, but it's fine as I'm not 100% what routing capabilities and classes is having the used version of the router.

2017-05-15 08:48 UTC, mgenov commented on frontend/src/components/AccountList/AccountListItem.js
> +export default (props) => {
.

2017-05-15 14:07 UTC, mgenov commented on frontend/src/components/AccountList/AccountList.js
> +                            account = {...account};
.

2017-05-16 14:08 UTC, mgenov commented
You have to squash your commits.

2017-05-16 14:21 UTC, IvelinYR commented
Commits are squashed.

2017-05-16 14:23 UTC, merged