Bank app alpha
clouway-incubator/bankapp pull request #9
Opened 2017-05-02 11:02 UTC by iliyanmotovski

Contains login with authentication, logout, cookies, deposit and update money to account if authenticated.

2017-05-02 22:25 UTC, mgenov requested changes

2017-05-02 22:25 UTC, mgenov commented on bank/handlers.go
> +func NewUserRepository(s mgo.Session, dbName string, colName ...string) *UserRepo {
HTTP package shouldn't know about Persistence related classes such as mgo.Session.

2017-05-02 22:25 UTC, mgenov commented on bank/handlers.go
> +	switch r.Method {
gorilla mux could route HTTP methods separately which removes boiling checks for methods in the handlers. 

Here is an example how this is accomplished in main.go: 
```golang
// connect to db 
db, err := mongo.NewDatabase(config)
if err != nil {
  log.Fatalf("could not connect to database due: %v", err)
}

// zone repository is created from db
zoneRepo := persistent.NewZoneRepository(db)


apiRoot := mux.NewRouter().PathPrefix("/api/v1").Subrouter()
apiRouter.Handle("/zones", api.CreateZone(zoneRepo)).Methods("POST")
apiRouter.Handle("/zones", api.FetchAllZones(zoneRepo)).Methods("GET")
apiRouter.Handle("/zones/{id}", api.FetchZoneByID(zoneRepo)).Methods("GET")
apiRouter.Handle("/zones/{id}", api.UpdateZone(zoneRepo)).Methods("PUT")
```

More information could be taken from:
http://www.gorillatoolkit.org/pkg/mux

2017-05-02 22:25 UTC, mgenov commented on bank/handlers.go
> +	err = us.InsertUser(u)
It's better to perform check queries instead of verifying of errors that are returned from the datastore during the insert.

2017-05-02 22:25 UTC, mgenov commented on cmd/bankapp/main.go
> +	http.Handle("/user/signup", SignUpHandlers.ThenFunc(repo.SignUpHandler))
Repository and handlers are different things.

2017-05-03 06:37 UTC, iliyanmotovski commented on bank/handlers.go
> +func NewUserRepository(s mgo.Session, dbName string, colName ...string) *UserRepo {
will try to refactor it

2017-05-03 06:37 UTC, iliyanmotovski commented on bank/handlers.go
> +	switch r.Method {
will read about and implement this solution

2017-05-04 08:28 UTC, closed without merging